export { SettingsService } from './settings/settings.service';
export { SidebarService } from './shared/sidebar.service';
export { SharedService } from './shared/shared.service';
export {DepartamentosService} from './pages/departamentos.service';
export {EmpleadosService} from './pages/empleados.service';
export {UsuarioService} from './pages/usuario.service';
export {ProveedorService} from './pages/proveedor.service';
export {ProductoService} from './pages/producto.service';
export {ProdproveeService} from './pages/prodprovee.service';
export {LineaService} from './pages/linea.service';
export {LineaProdService} from './pages/lineaprod.service';
export {EntradaempleadosService} from './pages/entradaempleados.service';
export {EntradalineaService} from './pages/entradalinea.service';
export {SalidalineaService} from './pages/salidalinea.service';
export {SalidaempleadoService} from './pages/salidaempleado.service';